[package]
name = "futureplay"
version = "0.1.0"
authors = ["Simon Perkins <simon.perkins@gmail.com>"]

[dependencies]
futures = { git = "https://github.com/alexcrichton/futures-rs" }
futures-cpupool = { git = "https://github.com/alexcrichton/futures-rs" }
